"""pubfig: Publication-quality figures with Matplotlib."""

from ._version import __version__
from .colors import (
    DEFAULT,
    JAMA,
    LANCET,
    NATURE,
    ORANGE_RED_4,
    SCIENCE,
    color_to_rgba,
    darken_color,
    get_palette,
    register_palette,
    show_palette,
)
from .export import batch_export, save_figure
from .plots import (
    area,
    bar,
    bar_scatter,
    box,
    bubble,
    clustermap,
    contour2d,
    corr_matrix,
    density,
    dimreduce,
    heatmap,
    histogram,
    line,
    paired,
    parallel_coordinates,
    pca_biplot,
    pr_curve,
    radar,
    raincloud,
    ridgeline,
    roc,
    sankey,
    scatter,
    stacked_bar,
    strip,
    violin,
)
from .specs import FigureSpec, get_figure_spec, list_figure_specs, register_figure_spec
from .themes import get_default_theme, get_theme, register_theme, set_default_theme

__all__ = [
    "__version__",
    # Themes
    "set_default_theme",
    "get_default_theme",
    "get_theme",
    "register_theme",
    # Colors
    "DEFAULT",
    "NATURE",
    "SCIENCE",
    "LANCET",
    "JAMA",
    "ORANGE_RED_4",
    "get_palette",
    "register_palette",
    "color_to_rgba",
    "darken_color",
    "show_palette",
    # Export
    "save_figure",
    "batch_export",
    # Figure specs
    "FigureSpec",
    "get_figure_spec",
    "register_figure_spec",
    "list_figure_specs",
    # Plots
    "bar",
    "bar_scatter",
    "stacked_bar",
    "box",
    "density",
    "histogram",
    "raincloud",
    "strip",
    "ridgeline",
    "violin",
    "line",
    "area",
    "radar",
    "scatter",
    "bubble",
    "contour2d",
    "paired",
    "heatmap",
    "corr_matrix",
    "clustermap",
    "dimreduce",
    "pca_biplot",
    "roc",
    "pr_curve",
    "sankey",
    "parallel_coordinates",
]
